### ISSUE TITLE
Improving unit test coverage

### ISSUE THREAD

**Issue by geetikabatra** [kubernetes-sigs/cluster-api-provider-vsphere#1392]
There is a lot of room for improvement in test coverage. 

Currently, the code coverage is `27%`

Following issues track the tasks

- [ ] [Test Coverage in pkg/util](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1421)
- [ ] [Test Coverage in pkg/services](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1420)
- [ ] [Test Coverage in pkg/record](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1419)
- [ ] [Test Coverage in pkg/manager](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1418)
- [ ] [Test Coverage in pkg/identity](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1417)

/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
Thanks Geetika for taking the initiative to add this issue, I think what would be helpful is adding tasks for a package based improvement of the test coverage. That way we could either have multiple folks work on it together and the issue seems to have an end goal we wanna reach.

**Comment by geetikabatra** [comment]
@srm09 Sure, I am coming with a list.

**Comment by aastha01chauhan** [comment]
@geetikabatra Hi! This project caught my eye while I was going through LFX mentorship projects list. I really liked the concept of it.  Would love to engage with the community and contribute here this spring.
