### ISSUE TITLE
Audit golangci-lint config

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2058]
Let's compare the golangci-lint config with the one from core CAPI and see if we should add more linters / config etc. (also potentially in core CAPI).

Some observations:
* I saw a few places where we didn't handle returned errors in CAPV. IIRC one of the linters enabled in core CAPI is catching that (not 100% sure). (we probably also need a corresponding exclude)
* We should configure the `importas` linter for at least the most important imports to get some consistency
```[tasklist]
### Tasks
- [x] enable configuration for `importas` (@chrischdi ) #2231
- [x] enable linter `containedctx` (@zhanggbj) #2297
- [x] enable linter `dupword` (@MrDXY) #2260
- [x] enable linter `errchkjson` (@MrDXY) #2273
- [x] enable linter `ginkgolinter` (@nunnatsa) #2282
- [x] enable linter `nolintlint` (@MrDXY) #2294
- [x] enable configuration for `gocritic` (@MrDXY) #2315
- [x] remove `apis/v1alpha3` from `skip-files:` (@adityabhatia) #2378
- [x] remove all additional exclusions below `FIXME: All below excludes should get removed over time.` #2383
- [ ] do a final diff
```

**Comment by chrischdi** [comment]
Let's tackle this in multiple steps:

1. One PR which sync's the `.golangci.yml` file to the core CAPI version.
  - When doing this, let's keep linters turned off (commented out) and enable them in follow-up PRs
  - Same applies for linter configuration
  - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2173
2. Enable new Linters and enabl;e configuration in multiple follow-up PRs. Doing this in a single PR would require too many code changes and would make it very hard for reviewers. 
  
  This would involve the following:
  * Enabling the following linters:
    - [ ] containedctx
    - [ ] dupword
    - [ ] errchkjson
    - [ ] ginkgolinter
  * Enabling configuration for the following linters
    - [ ] gocritic
    - [ ] importas
    - [ ] nolintlint

**Comment by lubronzhan** [comment]
I was debugging my PR and found out that it doesn't print any lines and code for specific lint error.

Found out [here](https://github.com/golangci/golangci-lint-action/issues/119) it could be fixed by `--out-format=colored-line-number`

Verified here https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/actions/runs/5791075333/job/15695267905?pr=2171
Gonna add another PR for that

**Comment by sbueringer** [comment]
@chrischdi Let's add a final step to diff against the core CAPI file again (just to make sure we didn't miss anything that we would want to have sync)

**Comment by chrischdi** [comment]
Update the above list and the initial MR

**Comment by chrischdi** [comment]
I already have a PR prepared as follow-up to enable the importas configuration.

**Comment by zhanggbj** [comment]
I'll start with this one :)

- [ ] containedctx

**Comment by sbueringer** [comment]
We can assign multiple people, just pick a linter and let us know :)

/help

**Comment by MrDXY** [comment]
I'll go with this one: 😊 
- [ ] dupword

**Comment by MrDXY** [comment]
I created another pr to track the following task. #2273  

- [ ]  enable linter `errchkjson`

**Comment by nunnatsa** [comment]
Hi. 

Just created a new PR to enable ginkgolinter; See #2282

**Comment by MrDXY** [comment]
Hi team, I will continue with `nolintlint`. 😄

**Comment by MrDXY** [comment]
Hi folks, I will proceed with enabling the configuration for 'gocritic'. 😄

**Comment by adityabhatia** [comment]
I will take this -  remove` apis/v1alpha3` from `skip-files:`

**Comment by chrischdi** [comment]
Took up some parts of

> remove all additional exclusions below `FIXME: All below excludes should get removed over time.` (Multiple PRs

in:

- #2058

**Comment by killianmuldoon** [comment]
I'm going to have a go at adding comments across the code under `FIXME`

**Comment by killianmuldoon** [comment]
I ran a diff between CAPV and CAPI golanglint-ci.yaml config files and there's nothing unexpected there. There's a tiny update to formatting in the CAPI file that will make diffing slightly easier - I'll raise that one in a PR.


Thanks everyone for your contributions!

@chrischdi I think we should close this if your happy with it - there's some follow-ups in #2384.
