### ISSUE TITLE
Ensure ownerRefs and refs are continuously reconciled

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2075]
There are various refs and ownerRefs managed by CAPV. The goal of this issue is to ensure that:
* they are always bumped to the latest apiVersion
* they are re-reconciled if the ownerRefs are dropped (which can e.g. happen via backup/restore)

We should also implement an e2e tests similar to the one in core CAPI to ensure this functionality doesn't break (quickstart + verification).

Some notes:
* Let's ensure this also covers Node IPAM (maybe in a second iteration)
* We should consider extending the core CAPI & CAPV e2e test to also ensure finalizers are re-applied

```[tasklist]
### Tasks
- [x] Add ownerReference validation for all CAPV types https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2209
- [x] Move to upstream CAPI utils for ownerReference checks https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2209
- [x] Ensure other refs are always updated
```

**Comment by sbueringer** [comment]
/assign @killianmuldoon 
(as discussed)

**Comment by killianmuldoon** [comment]
Added a tasklist to track the smaller tasks involved here.

**Comment by killianmuldoon** [comment]
AFAICT there are no references to objects that include an APIVersion in CAPV except for the `bootstrapRef` in the VSphereVM:

This Ref is always of type `Secret` from `corev1` so we don't have to update the ref.

There are additional references to Secret objects in CAPV - e.g. in the VSphereCluster and VSphereClusterIdentity, but the apiVersion is not part of those references.

**Comment by killianmuldoon** [comment]
That leaves the last follow-up items:
1)  **Let's ensure this also covers Node IPAM (maybe in a second iteration)**
Currently not tested as we have no tests for node IPAM. Should be added as part of that test. We can be confident it's unecessary for deprecating `v1alpha3` and `v1alpha4` as the IPAM code was added well after `v1beta1` was created. [Additionally the code for creating the IPAddressClaims looks good](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/fda748404cc40ecab62ea81fce96fa30eaf43dc2/controllers/vspherevm_ipaddress_reconciler.go#L139) - i.e. is using EnsureOwnerRef.

2) **We should consider extending the core CAPI & CAPV e2e test to also ensure finalizers are re-applied** 
Will open issues for this.


/close

**Comment by sbueringer** [comment]
Thank you! Sounds good
