### ISSUE TITLE
Improve CAPV logging

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2076]
Logging is a crucial to make it easier to understand controller behavior and troubleshoot issues.

While onboarding to CAPV we identified a few quickwins which should improve log quality significantly:
* It is a best practice in Kubernetes to add k/v pairs of the involved objects to a log line (https://cluster-api.sigs.k8s.io/developer/logging.html#keyvalue-pairs)
  * We should also add k/v pairs for all involved objects (and their owner hierarchy) that we retrieve at the beginning of the Reconcile
* We should also consistently use contextual logging (i.e. taking the logger from the ctx). This allows propagation of k/v pairs across the entire call stack
  * This also includes using the ctx that controller-runtime passes into the Reconcile func instead of some global ctx that is the same across Reconcile calls.

The overall goal of this issue is to improve the logs so troubleshooting becomes easier. Adding k/v pairs across the board will make it very easy to correlate logs e.g. for a specific Machine across controllers.

Additional notes:
* Let's take a look at how event recorders are setup in core CAPI vs CAPV
* Take a look at controller logger setup (e.g. regarding name). IIRC we shouldn't need any logger on the controllers though
* Audit all log calls for additional k/v pairs
* Ensure "Named" is set correctly on all controllers
* Let's double check the k/v pairs we add in core CAPI to ensure we can cross-reference everything
 

Prior art in core CAPI:
* https://github.com/kubernetes-sigs/cluster-api/pull/6150
* https://github.com/kubernetes-sigs/cluster-api/pull/7075
* https://github.com/kubernetes-sigs/cluster-api/pull/7152
* https://github.com/kubernetes-sigs/cluster-api/pull/7534

### Tasks

Concrete tasks for now (I have some follow-ups to audit, but let's do this afterwards):
* [x] Wait until context refactoring is done: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2295
* Refactor controllers (concrete tasks below):
  * [x] vmware/vspherecluster_reconciler.go
  * [x] clustermodule_reconciler.go
  * [x] serviceaccount_controller.go
  * [x] servicediscovery_controller.go
  * [x] vspherecluster_controller.go
  * [x] vspherecluster_reconciler.go
  * [x] vsphereclusteridentity_controller.go @Madhur97
    * #2426
  * [x] vspheredeploymentzone_controller.go & vspheredeploymentzone_controller_domain.go @Ankitasw 
  * [x] vspheremachine_controller.go @Ankitasw
    * #2395 
  * [x] vspherevm_controller.go & vspherevm_ipaddress_reconciler.go @adityabhatia 

* [x] Final audit (@sbueringer)

I took a quick look and there should be no overlap, so every tasks should ideally be a separate PR.

Tasks per controller:
* Adjust controller setup:
  * ControllerContext & Logger fields should be dropped from the Reconciler struct
  * Add Client & Recorder fields instead
  * If necessary we can add ControllerManagerContext (with a field name, no embedding to make the usage of the context explicit)
* Use logger from context.Context. Drop client & logger fields from structs like ClusterContext, MachineContext, ...
  * If there is currently no ctx available to get the logger from, add a ctx parameter to the current func
  * This will probably also lead to some compile errors when e.g. a MachineContext is passed into a client.Get. Please then pass in a context.Context instead.
* Add k/v pairs where appropriate and for all related object we "get" early in `Reconcile`

For more details see https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2352

**Comment by sbueringer** [comment]
cc @chrischdi @killianmuldoon @randomvariable @srm09 @yastij fyi

**Comment by Ankitasw** [comment]
Will pick  `vspheremachine_controller.go` once this [PR](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2376) is merged.

**Comment by Ankitasw** [comment]
Will pick ` vspheredeploymentzone_controller.go` and  `vspheredeploymentzone_controller_domain.go` next.

**Comment by killianmuldoon** [comment]
Two follow up tasks / things to check in logging:

- [ ] Remove `defer` logs where possible
- [ ] Remove checking log levels explicitly - e.g. `log.V(5).Enabled()`

Examples of this here: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2395#discussion_r1342507675

**Comment by chrischdi** [comment]
Thanks for picking `vsphereclusteridentity_controller.go` @Madhur97 👍

**Comment by adityabhatia** [comment]
I can pickup `vspherevm_controller.go & vspherevm_ipaddress_reconciler.go`
