### ISSUE TITLE
Tasks for v1.8 release cycle

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2175]
Notes:
* This issue has been created based on the template in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2147
* We'll do these steps for v1.8 retroactively / verify we did everything important

Please see the corresponding sections in [release-tasks.md](https://github.com/sbueringer/cluster-api-provider-vsphere/blob/pr-update-release-documentation/docs/release/release-tasks.md) for documentation of individual tasks.  

## Tasks

Early in the cycle:
* [ ] [Prepare main branch for development of the new release](https://github.com/sbueringer/cluster-api-provider-vsphere/blob/pr-update-release-documentation/docs/release/release-tasks.md#prepare-main-branch-for-development-of-the-new-release)
* [ ] [Remove previously deprecated code](https://github.com/sbueringer/cluster-api-provider-vsphere/blob/pr-update-release-documentation/docs/release/release-tasks.md#remove-previously-deprecated-code)

If and when necessary:
* [ ] [Bump the Kubernetes version](https://github.com/sbueringer/cluster-api-provider-vsphere/blob/pr-update-release-documentation/docs/release/release-tasks.md#optional-bump-the-kubernetes-version)

Late in the cycle:
* [ ] [Bump dependencies](https://github.com/sbueringer/cluster-api-provider-vsphere/blob/pr-update-release-documentation/docs/release/release-tasks.md#bump-dependencies)
* [ ] [Create the new release branch](https://github.com/sbueringer/cluster-api-provider-vsphere/blob/pr-update-release-documentation/docs/release/release-tasks.md#create-a-release-branch)
* [ ] [opt] [Cut beta/rc releases](https://github.com/sbueringer/cluster-api-provider-vsphere/blob/pr-update-release-documentation/docs/release/release-tasks.md#repeatedly-cut-a-release)
* [ ] [Cut the minor release](https://github.com/sbueringer/cluster-api-provider-vsphere/blob/pr-update-release-documentation/docs/release/release-tasks.md#repeatedly-cut-a-release)

Continuously:
* [Reduce the amount of flaky tests](https://github.com/sbueringer/cluster-api-provider-vsphere/blob/pr-update-release-documentation/docs/release/release-tasks.md#continuously-reduce-the-amount-of-flaky-tests)

**Comment by sbueringer** [comment]
I went over the tasks above and the following is not done yet

* Prepare main branch for development of the new release
  * Basically we have to go over all steps and make sure they are done for v1.9 and then backport accordingly
    * Refactor e2e test folder structure + fixup versions in the entire test folder structure
    * Enable clusterctl upgrade tests again for n-1 => n & n-2 => n (should also use the corresponding n-2, n-1 core CAPI versions)
* Create the new release branch
  * We have to fast-forward the release-1.8 release-branch to v1.8.0
  * Update the milestone applier config: main should be v1.9
  * Add Trivy scan for release-1.8

My suggestion:
* Prepare main branch for development of the new release => we'll carry this over to the next release and then backport (there should be nothing critical missing for the release tomorrow)
* Create the new release branch => will be done tomorrow after the release

@killianmuldoon WDYT? (also let me know if you want to talk about the folder structure etc. but it should be just the same as in core CAPI afterwards)

**Comment by killianmuldoon** [comment]
Just to clarify 

> Basically we have to go over all steps and make sure they are done for v1.9 and then backport accordingly 

should be v1.8, right?

**Comment by sbueringer** [comment]
Caught up on all the tasks with the release today.

@killianmuldoon I'm going to open a new tracking issue for v1.9. I think we can then combine the restructuring your planning with "Prepare main branch for development of the new release" (not necessarily in the same PR but it's closely related, whatever works for you)
