### ISSUE TITLE
Bump to Cluster API v1.7

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2549]
Just an umbrella issue to collect follow-up tasks once we bumped to Cluster API v1.7 (to be released in April 2024):

* [x] Ensure we don't add `"component", "remote/clustercachetracker"` twice. Since https://github.com/kubernetes-sigs/cluster-api/pull/9813 it is added by the CCT automatically
  * PR: #2863
* [x] Bump to Go 1.21
  * [x] PR https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2741
  * [x] Cherry-pick into release-1.9, release-1.8, release-1.7
    * #2744
    * #2743
    * #2745
* [x] Drop test/infrastructure/tmp added in #2613
  * Done. Didn't lookup which PR but it's not important
* [x] Adapt to #2865 @zhanggbj 
* [ ] Start using release markers in our e2e config: #2895 @zhanggbj

**Comment by zhanggbj** [comment]
Hey @sbueringer,
I would like to work on this one if it is still available

- [ ] Adapt to https://github.com/kubernetes-sigs/cluster-api/pull/9946

**Comment by sbueringer** [comment]
@zhanggbj sounds good. Thank you!

**Comment by zhanggbj** [comment]
Hey @sbueringer ,

I just want to double-check the target of this item.

- [ ] Start using release markers in our e2e config: https://github.com/kubernetes-sigs/cluster-api/pull/9265

The intention is to replace the current hard-coded [providers' versions ](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/test/e2e/config/vsphere.yaml#L32)with release markers, so that e2e test could fetch the latest and stable releases?

And if yes, I would like to pick up this one :-)

**Comment by sbueringer** [comment]
Closing this issue. The mandatory parts of the CAPI bump are done. I see #2895 more as an async follow-up (that we'll complete in the next 1-2 weeks)
