### ISSUE TITLE
Tasks for v1.11 release cycle

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2945]
Please see the corresponding sections in [release-tasks.md](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md) for documentation of individual tasks.  

## Tasks

Early in the cycle:
* [x] [Prepare main branch for development of the new release](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#prepare-main-branch-for-development-of-the-new-release) @chrischdi 
  * PR: #2950
* [x] [Remove previously deprecated code](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#remove-previously-deprecated-code)

Release-specific tasks:
* [x] Remove keep alive handler deprecated in: #2896 @zhanggbj 
  * PR: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2984
* [x] Adopt clusterctl upgrade tests to: https://github.com/kubernetes-sigs/cluster-api/pull/10639 (once available for CAPV)
  * PR: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3050

After the Kubernetes minor release:
* [x] Bump the Kubernetes version 
  * [x] Publish new OVA images
    * Build new OVA images via image-builder
    * Make them available in the CI environment
    * Publish them via a GitHub release (e.g. [templates/v1.30.0](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/tag/templates/v1.30.0))
    * Update `README.md` accordingly
    * PR: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3157
  * [x] Bump e2e tests
    * Add the new image to `internal/test/helpers/vcsim/model.go`
    * Bump template env variables in `test/e2e/config/vsphere.yaml` and `test/e2e/config/config-overrides-example.yaml`
      * Also bump `KUBERNETES_VERSION_*`
      * Also bump `KUBERNETES_VERSION_LATEST_CI` to the next minor version
      * Also bump `CPI_IMAGE_K8S_VERSION`
      * Regenerate `packaging/flavorgen/cloudprovider/cpi/cpi.yaml` by checking out the release tag of `https://github.com/kubernetes/cloud-provider-vsphere` and running `helm template charts/vsphere-cpi`
    * Bump in:
      * `test/e2e/data/infrastructure-vsphere-govmomi/main/clusterclass/patch-vsphere-template.yaml`
      * `test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/patch-vsphere-template.yaml` 
    * PR: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3154 
  * [x] Update ProwJob configuration accordingly
    * PR: https://github.com/kubernetes/test-infra/pull/33305

Late in the cycle:
* [x] [Bump dependencies](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#bump-dependencies)
  * #3107 
  * #3119
  * #3127
  * #3129
  * #3155
  * [x] Adopt:
    * [x] https://github.com/kubernetes-sigs/cluster-api/pull/10880
    * [x] https://github.com/kubernetes-sigs/cluster-api/pull/10883
* [x] [Create the new release branch](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#create-a-release-branch) @ 1st August
* [x] [opt] [Cut beta/rc releases](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#cut-a-release)
  * [x] [v1.11.0-beta.0](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/tag/v1.11.0-beta.0)
  * [x] [v1.11.0-beta.1](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/tag/v1.11.0-beta.1)
  * [x] [v1.11.0-rc.0](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/tag/v1.11.0-rc.0) @ 1st August
  * [x] [v1.11.0-rc.1](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/tag/v1.11.0-rc.1) @ 7th August
* [x] [Cut the minor release](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#cut-a-release) @ 14th August

Continuously:
* [Reduce the amount of flaky tests](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#continuously-reduce-the-amount-of-flaky-tests)

**Comment by sbueringer** [comment]
@chrischdi Whoever takes [Prepare main branch for development of the new release](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#prepare-main-branch-for-development-of-the-new-release), let's take the chance to finalize the corresponding doc section after we finalized what exactly we have to do

**Comment by chrischdi** [comment]
> @chrischdi Whoever takes [Prepare main branch for development of the new release](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md?rgh-link-date=2024-04-25T12%3A27%3A27Z#prepare-main-branch-for-development-of-the-new-release), let's take the chance to finalize the corresponding doc section after we finalized what exactly we have to do in the PR

PR for docs update: #2951

**Comment by sbueringer** [comment]
@adityabhatia @zhanggbj I think we can go ahead with "Remove keep alive handler deprecated" if someone has time / is looing for a bit of work :)

**Comment by zhanggbj** [comment]
@sbueringer I would like to work on it :-)

**Comment by fabriziopandini** [comment]
@sbueringer is [Bump the Kubernetes version](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#optional-bump-the-kubernetes-version) when we start testing Kubernetes 1.31?

**Comment by sbueringer** [comment]
@fabriziopandini Yes

**Comment by sbueringer** [comment]
Removed the test sub-task from this issue, will add it to a new umbrella issue

**Comment by sbueringer** [comment]
@chrischdi Assigned to both of us and added to the v1.11 milestone. Please keep especially building the OVA on your radar as it's one of the tasks we have to do after the 1.30 release that takes the most time until we can cut CAPV v1.11

**Comment by sbueringer** [comment]
@chrischdi Added a new sub-task to adopt recent CAPI changes in CAPV

**Comment by sbueringer** [comment]
Checked diff to latest rc. Nothing to add to the highlights

**Comment by chrischdi** [comment]
All PR's for v1.31 should be prepared now.

Waiting for the v1.31.0 release.

**Comment by sbueringer** [comment]
All done for v1.11 (updated the tasks above)

**Comment by chrischdi** [comment]
So should we close this one?

**Comment by sbueringer** [comment]
I wasn't sure because of v1.11.1. But let's drop this from this issue and just track it between us?

**Comment by sbueringer** [comment]
Didn't get a notification when you added the 👍  :)

/close
