### ISSUE TITLE
Tasks for v1.12 release cycle

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#3084]
Please see the corresponding sections in [release-tasks.md](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md) for documentation of individual tasks.  

## Tasks

Early in the cycle:
* [x] [Prepare main branch for development of the new release](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#prepare-main-branch-for-development-of-the-new-release): https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3159
* [x] [Remove previously deprecated code](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#remove-previously-deprecated-code)

Release-specific tasks:
* [ ] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/3022
* TODO

After the Kubernetes minor release:
* [x] Bump the Kubernetes version 
  * [x] Publish new OVA images
    * Build new OVA images via image-builder
    * Make them available in the CI environment
    * Publish them via a GitHub release (e.g. [templates/v1.30.0](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/tag/templates/v1.30.0))
    * Update `README.md` accordingly
    * #3294
    * #3297
  * [x] Bump e2e tests
    * Add the new image to `internal/test/helpers/vcsim/model.go`
    * Bump template env variables in `test/e2e/config/vsphere.yaml` and `test/e2e/config/config-overrides-example.yaml`
      * Also bump `KUBERNETES_VERSION_*`
      * Also bump `KUBERNETES_VERSION_LATEST_CI` to the next minor version
      * Also bump `CPI_IMAGE_K8S_VERSION`
      * Regenerate `packaging/flavorgen/cloudprovider/cpi/cpi.yaml` by checking out the release tag of `https://github.com/kubernetes/cloud-provider-vsphere` and running `helm template charts/vsphere-cpi`
    * Bump in:
      * `test/e2e/data/infrastructure-vsphere-govmomi/main/clusterclass/patch-vsphere-template.yaml`
      * `test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/patch-vsphere-template.yaml` 
    * #3294
    * #3297
  * [x] Update ProwJob configuration accordingly
    * https://github.com/kubernetes/test-infra/pull/33945

Late in the cycle:
* [x] [Bump dependencies](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#bump-dependencies)
* [x] [Create the new release branch](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#create-a-release-branch)
* [x] [opt] [Cut beta/rc releases](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#cut-a-release)
  * [x] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3249
  * [x] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3259
  * [x] #3264
  * [x] #3263 
  * [x] #3271
  * [x] #3269
  * [x] #3284
  * [x] #3277

* [x] [Cut the minor release](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#cut-a-release)

Continuously:
* [Reduce the amount of flaky tests](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#continuously-reduce-the-amount-of-flaky-tests)

Probably for the next cycle:
* [ ] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/3221

**Comment by sbueringer** [comment]
Checked for deprecations, nothing to do for this cycle

**Comment by sbueringer** [comment]
@chrischdi @fabriziopandini (no rush) seems like we're done? (So we can create a new issue for 1.13 and move over open sub-tasks?)

**Comment by sbueringer** [comment]
Created a v1.13 issue and moved over the open sub-tasks from above: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/3307

/close
