### ISSUE TITLE
Tasks for v1.13

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#3307]
Please see the corresponding sections in [release-tasks.md](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md) for documentation of individual tasks.  

## Tasks

Early in the cycle:
* [x] [Prepare main branch for development of the new release](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#prepare-main-branch-for-development-of-the-new-release)
  * [x] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3321
* [x] [Remove previously deprecated code](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#remove-previously-deprecated-code)

Release-specific tasks:
* [x] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/3221
* [x] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/3022
* [x] Anything else?

After the CAPI beta & RC release:
* [x] Bump the CAPI version 
  * Bumped to rc.0 #3419 

After the Kubernetes beta & RC release:
* [x] Bump the Kubernetes version 
  * Bumped to rc.1 #3426 

After the CPI beta & RC release:
* [x] Bump the CPI version 
  * #3269 

After the Kubernetes minor release:
* [x] Bump the Kubernetes version 
  * [x] Publish new OVA images
    * Build new OVA images via image-builder
    * Make them available in the CI environment
    * Publish them via a GitHub release (e.g. [templates/v1.30.0](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/tag/templates/v1.30.0))
    * Update `README.md` accordingly
  * [x] Bump e2e tests
    * PR: #3428 
    * Cherry-pick PR: #3429
    * Add the new image to `internal/test/helpers/vcsim/model.go`
    * Bump template env variables in `test/e2e/config/vsphere.yaml` and `test/e2e/config/config-overrides-example.yaml`
      * Also bump `KUBERNETES_VERSION_*`
      * Also bump `KUBERNETES_VERSION_LATEST_CI` to the next minor version
      * Also bump `CPI_IMAGE_K8S_VERSION`
      * Regenerate `packaging/flavorgen/cloudprovider/cpi/cpi.yaml` by checking out the release tag of `https://github.com/kubernetes/cloud-provider-vsphere` and running `helm template charts/vsphere-cpi`
    * Bump in:
      * `test/e2e/data/infrastructure-vsphere-govmomi/main/clusterclass/patch-vsphere-template.yaml`
      * `test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/patch-vsphere-template.yaml` 
  * [x] Update ProwJob configuration accordingly
    * PR: https://github.com/kubernetes/test-infra/pull/34688

Late in the cycle:
* [x] [Bump dependencies](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#bump-dependencies)
* [x] [Create the new release branch](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#create-a-release-branch)
* [x] [opt] [Cut beta/rc releases](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#cut-a-release)
* [x] [Cut the minor release](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#cut-a-release)

Continuously:
* [Reduce the amount of flaky tests](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#continuously-reduce-the-amount-of-flaky-tests)

**Comment by sbueringer** [comment]
Release notes as of beta.0

```
## Highlights

- Tested with Kubernetes v1.33 & cloud-provider-vsphere v1.33
- Based on Cluster API v1.10
- Bumped to Go 1.23, controller-runtime v0.20, k8s.io/* v0.32, controller-gen v0.17
- Implemented v1beta2 conditions for all CRDs
- Improved & extended e2e test coverage, e.g. added Scale and NodeDrain e2e test 

govmomi mode:
- Add ability to add new data disks to VM during clone process (#3214 ##3332)
- Add VM naming strategy (#3286)
```

**Comment by sbueringer** [comment]
HIghlights (https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/3307#issuecomment-2743365026) are still up-to-date as of rc.0
